### ISSUE TITLE
Can't get it to work, error everytime

### ISSUE THREAD

**Issue by akidfromtheuk** [vicr123/AstralMod#14]
Keep getting this error 

module.js:471
    throw err;
    ^

Error: Cannot find module './keys.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\BGD\Desktop\astralmod\bot.js:22:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by FriendsNone** [comment]
Error: Cannot find module './keys.js'

Make a file named keys.js. I don't know what are the contents, ask the devs. :D

**Comment by akidfromtheuk** [comment]
Ok, Thanks...
